default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  host: postgres
  port: 5432

development:
  <<: *default
  database: prog_image_development

test:
  <<: *default
  database: prog_image_test

production:
  <<: *default
  database: prog_image_production
